spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${USER_SERVICE_URL:http://localhost:8084}
          jwk-set-uri: ${USER_SERVICE_URL:http://localhost:8084}/oauth2/jwks